### ISSUE TITLE
Giter8 version is should be detected from build.properties

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt-giter8-resolver#11]
## steps

In `project/build.properties`, I can write:

```
sbt.version=0.13.16
giter8.version=0.10.0
```

## expectation

Calling `sbt new eed3si9n/declare-version.g8`, it will pick up Giter8 version 0.10.0, and run it.

## notes

Ref https://github.com/sbt/sbt-giter8-resolver/pull/8 and https://github.com/foundweekends/giter8/pull/303

**Comment by xuwei-k** [comment]
https://github.com/sbt/sbt-giter8-resolver/pull/18

**Comment by eed3si9n** [comment]
This is done, I guess.
