### ISSUE TITLE
Version uploaded to Maven Central Repository does not exist in GitHub repository (0.13.1)

### ISSUE THREAD

**Issue by magnolia-k** [sbt/sbt-giter8-resolver#21]
![image](https://user-images.githubusercontent.com/1701138/182606499-b2e15cbf-b6d3-42fb-bc23-f0351ba27a4e.png)
![image](https://user-images.githubusercontent.com/1701138/182607955-78cb9c87-18fd-4a45-b87b-facd976ea2c7.png)

**Comment by eed3si9n** [comment]
Sorry, I just pushed them https://github.com/sbt/sbt-giter8-resolver/releases/tag/v0.13.1
