### ISSUE TITLE
git URL test should check for `.g8.git` not `.g8`

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt-giter8-resolver#7]
https://github.com/sbt/sbt-giter8-resolver/blob/88a81fe317f79334278bbfff2c9a7e55b3f89a02/src/main/scala/sbt/Giter8TemplateResolver.scala#L26

**Comment by dwijnand** [comment]
Fixed in https://github.com/sbt/sbt-giter8-resolver/pull/15.
